devs4good/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path("cadastro/", views.cadastro, name="cadastro"),
    path("login/", views.login, name="login"),
    path("index/", views.index, name="index"),
    path("funcionarios/", views.funcionarios, name="funcionarios"),
    path('funcionario/<int:pk>/', views.funcionario_detail, name='funcionario_detail'),
    path("linguagens/", views.lista_linguagens, name="lista_linguagens"),
    path("novo_funcionario/", views.novo_funcionario, name="novo_funcionario"),
    path("cargos/", views.lista_cargos, name="lista_cargos"),
    path("novo_cargo/", views.novo_cargo, name="novo_cargo"),
    path("nova_linguagem/", views.nova_linguagem, name="nova_linguagem"),
    path("logout/", views.logout, name="logout"),
    path("funcionarios_filtro_salario/", views.funcionarios_filtro_salario, name="funcionarios_filtro_salario"),
    # Outras rotas do aplicativo devs4good podem ser definidas aqui
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include  # Importe o include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('devs4good.urls')),  # Inclua as URLs do seu aplicativo
]

devs4good/models.py
from django.db import models


class Cargo(models.Model):
    nome = models.CharField(max_length=100)
    salario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome


class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    linguagens = models.ManyToManyField(LinguagemProgramacao)

    def __str__(self):
        return self.nome


class InformacoesFuncionario(models.Model):
    funcionario = models.OneToOneField(Funcionario, on_delete=models.CASCADE)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=2)
    idade = models.IntegerField()
    frase_preferida = models.TextField()
    pokemon_preferido = models.CharField(max_length=20)

    def __str__(self):
        return f"Informações de {self.funcionario.nome}"

devs4good/forms.py
from django import forms
from .models import Cargo, LinguagemProgramacao, Funcionario, InformacoesFuncionario


class FuncionarioForm(forms.ModelForm):
    linguagens = forms.ModelMultipleChoiceField(
        queryset=LinguagemProgramacao.objects.all(), widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Funcionario
        fields = ["nome", "cargo", "linguagens"]


class InformacoesFuncionarioForm(forms.ModelForm):
    class Meta:
        model = InformacoesFuncionario
        fields = ["cidade", "estado", "idade", "frase_preferida", "pokemon_preferido"]


class CargoForm(forms.ModelForm):
    class Meta:
        model = Cargo
        fields = ["nome", "salario"]


class LinguagensForm(forms.ModelForm):
    class Meta:
        model = LinguagemProgramacao
        fields = ["nome"]

devs4good/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Funcionario, LinguagemProgramacao, Cargo
from .forms import (
    FuncionarioForm,
    InformacoesFuncionarioForm,
    CargoForm,
    LinguagensForm,
)
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


@login_required
def index(request):
    return render(request, "devs4good/index.html")


def inicio(request):
    return render(
        request, "devs4good/inicio.html", {"messages": messages.get_messages(request)}
    )


@login_required
def funcionarios(request):
    funcionarios = Funcionario.objects.all().order_by("pk")
    return render(
        request, "devs4good/funcionarios.html", {"funcionarios": funcionarios}
    )


@login_required
def funcionario_detail(request, pk):
    funcionario = get_object_or_404(Funcionario, pk=pk)
    return render(
        request, "devs4good/funcionario_detail.html", {"funcionario": funcionario}
    )


@login_required
def lista_linguagens(request):
    linguagens = LinguagemProgramacao.objects.all()
    return render(
        request, "devs4good/lista_linguagens.html", {"linguagens": linguagens}
    )


@login_required
def nova_linguagem(request):
    if request.method == "POST":
        form_linguagem = LinguagensForm(request.POST)

        if form_linguagem.is_valid():
            form_linguagem.save()
            return redirect("index")
    else:
        form_linguagem = LinguagensForm()

    return render(
        request,
        "devs4good/nova_linguagem.html",
        {
            "form_linguagem": form_linguagem,
        },
    )


@login_required
def novo_funcionario(request):
    if request.method == "POST":
        form_funcionario = FuncionarioForm(request.POST)
        form_informacoes = InformacoesFuncionarioForm(request.POST)
        if form_funcionario.is_valid() and form_informacoes.is_valid():
            funcionario = form_funcionario.save()
            informacoes = form_informacoes.save(commit=False)
            informacoes.funcionario = funcionario
            informacoes.save()
            return redirect("index")
    else:
        form_funcionario = FuncionarioForm()
        form_informacoes = InformacoesFuncionarioForm()

    return render(
        request,
        "devs4good/novo_funcionario.html",
        {
            "form_funcionario": form_funcionario,
            "form_informacoes": form_informacoes,
        },
    )


@login_required
def lista_cargos(request):
    cargos = Cargo.objects.all()
    return render(request, "devs4good/lista_cargos.html", {"cargos": cargos})


@login_required
def novo_cargo(request):
    if request.method == "POST":
        form_cargo = CargoForm(request.POST)

        if form_cargo.is_valid():
            form_cargo.save()
            return redirect("index")
    else:
        form_cargo = CargoForm()

    return render(
        request,
        "devs4good/novo_cargo.html",
        {
            "form_cargo": form_cargo,
        },
    )


def cadastro(request):
    if request.method == "GET":
        return render(request, "devs4good/cadastro.html")
    else:
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")

        userExists = User.objects.filter(username=username).first()
        emailExists = User.objects.filter(email=email).first()

        if userExists:
            return HttpResponse("Usuário com esse nome já existe")
        if emailExists:
            return HttpResponse("Email já cadastrado")

        user = User.objects.create_user(
            username=username, email=email, password=password
        )
        user.save()

        return redirect("index")


def login(request):
    if request.method == "GET":
        return render(request, "devs4good/login.html")
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")

        validUser = authenticate(username=username, password=password)

        if validUser is not None:
            auth_login(request, validUser)
            return redirect("index")
        else:
            return HttpResponse("Usuário ou senha inválidos")


def logout(request):
    auth_logout(request)
    messages.success(request, "Você foi deslogado com sucesso.")
    return redirect("inicio")


def funcionarios_filtro_salario(request):
    valor_minimo = request.GET.get("minimo")
    valor_maximo = request.GET.get("maximo")

    funcionarios = Funcionario.objects.all()

    if valor_minimo:
        funcionarios = funcionarios.filter(cargo__salario__gte=valor_minimo)

    if valor_maximo:
        funcionarios = funcionarios.filter(cargo__salario__lte=valor_maximo)

    return render(
        request,
        "devs4good/funcionarios_filtro_salario.html",
        {"funcionarios": funcionarios},
    )

devs4good/templates/devs4good/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        input {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <form action="{% url 'cadastro' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Username" name="username">
        <input type="text" placeholder="Email" name="email">
        <input type="password" placeholder="Password" name="password">
        <input type="submit" value="Cadastrar e Entrar">
    </form>
</body>
</html>

devs4good/templates/devs4good/funcionario_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalhes do Funcionário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #333;
            margin-bottom: 10px;
        }
        .detail-label {
            font-weight: bold;
            color: #555;
        }
        .detail-value {
            color: #333;
            margin-left: 10px;
        }
        .detail-section {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>{{ funcionario.nome }}</h2>
        
        <div class="detail-section">
            <p><span class="detail-label">Cargo:</span> <span class="detail-value">{{ funcionario.cargo }}</span></p>
            <p><span class="detail-label">Linguagens:</span> 
                {% for linguagem in funcionario.linguagens.all %}
                    <span class="detail-value">{{ linguagem.nome }}{% if not forloop.last %}, {% endif %}</span>
                {% endfor %}
            </p>
            <p><span class="detail-label">Salário:</span> <span class="detail-value">{{ funcionario.cargo.salario }}</span></p>
        </div>

        <div class="detail-section">
            <p><span class="detail-label">Cidade:</span> <span class="detail-value">{{ funcionario.informacoesfuncionario.cidade }}</span></p>
            <p><span class="detail-label">Estado:</span> <span class="detail-value">{{ funcionario.informacoesfuncionario.estado }}</span></p>
            <p><span class="detail-label">Idade:</span> <span class="detail-value">{{ funcionario.informacoesfuncionario.idade }}</span></p>
        </div>

        <div class="detail-section">
            <p><span class="detail-label">Frase Preferida:</span> <span class="detail-value">{{ funcionario.informacoesfuncionario.frase_preferida }}</span></p>
            <p><span class="detail-label">Pokemon Preferido:</span> <span class="detail-value">{{ funcionario.informacoesfuncionario.pokemon_preferido }}</span></p>
        </div>
    </div>
</body>
</html>

devs4good/templates/devs4good/funcionarios.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Funcionários</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            text-align: center; /* Centraliza todo o conteúdo dentro do container */
        }
        h2 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        .new-button {
            margin-top: 20px;
            display: inline-block;
            background-color: #007bff;
            text-decoration: none;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .new-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Lista de Funcionários</h2>
        <table>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cargo</th>
                </tr>
            </thead>
            <tbody>
                {% for funcionario in funcionarios %}
                <tr>
                    <td><a href="{% url 'funcionario_detail' funcionario.pk %}">{{ funcionario.nome }}</a></td>
                    <td>{{ funcionario.cargo }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="new-button" href="{% url 'novo_funcionario' %}">Cadastrar Novo Funcionário</a><br>
    </div>
</body>
</html>

devs4good/templates/devs4good/funcionarios_filtro_salario.html
<!DOCTYPE html>
<html>
<head>
    <title>Funcionários com Salário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #333;
        }
        form {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input[type="number"] {
            width: 100px;
            padding: 5px;
            border: 1px solid #ccc;
        }
        button {
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
        }
        ul {
            list-style: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Funcionários com Salário</h2>
        
        <form method="get">
            <label for="minimo">Salário Mínimo:</label>
            <input type="number" name="minimo" id="minimo">
            <br>
            <label for="maximo">Salário Máximo:</label>
            <input type="number" name="maximo" id="maximo">
            <br>
            <button type="submit">Filtrar</button>
        </form>
        
        <ul>
            {% for funcionario in funcionarios %}
                <li>{{ funcionario.nome }} - Salário: R$ {{ funcionario.cargo.salario }}</li>
            {% empty %}
                <li>Nenhum funcionário encontrado com os critérios de filtro.</li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

devs4good/templates/devs4good/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Devs4Good - Empresa</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        
        a {
            display: block;
            text-align: center;
            font-size: 18px;
            color: #007bff;
            text-decoration: none;
            margin-bottom: 10px;
            transition: color 0.3s ease;
            padding: 10px;
            border: 1px solid #007bff;
            border-radius: 5px;
        }
        
        a:hover {
            color: #0056b3;
            background-color: #f0f0f0;
        }
        
        .logout-link {
            text-align: center;
            display: block;
            margin-bottom: 20px;
        }
        
        .link {
            color: red;
        }
        
    </style>
</head>
<body>
    <div class="container">
        <div class="logout-link">
        </div>
        <h1>Devs4Good - Empresa</h1>
        <a href="{% url 'funcionarios' %}">Funcionários</a>
        <a href="{% url 'lista_linguagens' %}">Linguagens</a>
        <a href="{% url 'lista_cargos' %}">Cargos</a>
        <a href="{% url 'funcionarios_filtro_salario' %}">Filtrar Funcionários por Salário</a>
        <a class="link" href="{% url 'logout' %}">Logout</a>
    </div>
</body>
</html>

devs4good/templates/devs4good/inicio.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Linguagens e Funcionários</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        h1 {
            color: #333;
            margin-bottom: 20px;
        }
        a {
            display: inline-block;
            margin: 10px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="message success">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
        
        <h1>Seja Bem Vindo à Empresa Devs4Good</h1>
        <a href="{% url 'cadastro' %}">Cadastro</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
    
</body>
</html>

devs4good/templates/devs4good/lista_cargos.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Cargos e Funcionários</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        .new-button {
            display: block;
            width: 200px;
            margin: 20px auto;
            padding: 10px;
            text-align: center;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .new-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Lista de Cargos e Funcionários</h2>
        <table>
            <thead>
                <tr>
                    <th>Cargo</th>
                    <th>Salário</th>
                    <th>Funcionários</th>
                </tr>
            </thead>
            <tbody>
                {% for cargo in cargos %}
                <tr>
                    <td>{{ cargo.nome }}</td>
                    <td>{{ cargo.salario }}</td>
                    <td>
                        {% if cargo.funcionario_set.exists %}
                            <ul>
                                {% for funcionario in cargo.funcionario_set.all %}
                                    <li>{{ funcionario.nome }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Nenhum funcionário associado a este cargo.</p>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="new-button" href="{% url 'novo_cargo' %}">Cadastrar Novo Cargo</a><br>
    </div>
</body>
</html>

devs4good/templates/devs4good/lista_linguagens.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Linguagens e Funcionários</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        h2 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        .new-button {
            display: block;
            width: 200px;
            margin: 20px auto;
            padding: 10px;
            text-align: center;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .new-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Lista de Linguagens e Funcionários</h2>
        <table>
            <thead>
                <tr>
                    <th>Linguagem</th>
                    <th>Funcionários</th>
                </tr>
            </thead>
            <tbody>
                {% for linguagem in linguagens %}
                <tr>
                    <td>{{ linguagem.nome }}</td>
                    <td>
                        {% if linguagem.funcionario_set.exists %}
                            <ul>
                                {% for funcionario in linguagem.funcionario_set.all %}
                                    <li>{{ funcionario.nome }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Nenhum funcionário associado a esta linguagem.</p>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="new-button" href="{% url 'nova_linguagem' %}">Cadastrar Nova Linguagem</a><br>
    </div>
</body>
</html>

devs4good/templates/devs4good/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        input {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>

    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="username" name="username">
        <input type="password" placeholder="password" name="password">
        <input type="submit" value="Logar e entrar">

    </form>
</body>
</html>

devs4good/templates/devs4good/nova_linguagem.html
<!DOCTYPE html>
<html>
<head>
    <title>Nova Linguagem</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        h2 {
            color: #333;
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }
        input[type="text"] {
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin-bottom: 10px;
            width: 100%;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Nova Linguagem</h2>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form_linguagem.nome.id_for_label }}">Nome:</label>
            {{ form_linguagem.nome }}
            <button type="submit">Salvar</button>
        </form>
    </div>
</body>
</html>

devs4good/templates/devs4good/novo_cargo.html
<!DOCTYPE html>
<html>
<head>
    <title>Novo Funcionário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        h2 {
            color: #333;
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }
        input[type="text"], input[type="number"] {
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin-bottom: 10px;
            width: 100%;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Novo Cargo</h2>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form_cargo.nome.id_for_label }}">Nome:</label>
            {{ form_cargo.nome }}
            <label for="{{ form_cargo.salario.id_for_label }}">Salário:</label>
            {{ form_cargo.salario }}
            <button type="submit">Salvar</button>
        </form>
    </div>
</body>
</html>

devs4good/templates/devs4good/novo_funcionario.html
<!DOCTYPE html>
<html>
<head>
    <title>Novo Funcionário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #333;
            margin-bottom: 20px;
        }
        form {
            display: grid;
            gap: 10px;
        }
        label {
            font-weight: bold;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Novo Funcionário</h2>
        <form method="post">
            {% csrf_token %}
            {{ form_funcionario.as_p }}
            {{ form_informacoes.as_p }}
            <button type="submit">Salvar</button>
        </form>
    </div>
</body>
</html>